### PR TITLE
cbits: Namespace batch_point_buffer.

### PR DESCRIPTION
**Pull request by shlevy**

### CODE REVIEW

**Comment by shlevy** [comment]
Draft PR until I've confirmed our use case is working.

**Comment by kazu-yamamoto** [comment]
I have merged #7 and #8 linearly. 
While this work, I made a mistake.
So, I did `git push -f origin master`.
I'm very sorry.

@shlevy @angerman I you like the current `master`, I will make a new release.

**Comment by shlevy** [comment]
Testing now, will report back!

**Comment by shlevy** [comment]
@kazu-yamamoto It's working, thank you! A new release, and perhaps even deprecating the current one, would be great.

**Comment by kazu-yamamoto** [comment]
@shlevy All done.

**Pull request closed without merging**
